apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.ingressname}}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.name}}
          servicePort: {{ .Values.port}}          
      